language: ruby
rvm:
  - 2.2.0
  - 2.1.5
  - 2.1.4
  - 2.1.3
  - 2.1.2
  - 2.1.1
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - 1.8.7

  fast_finish: true

  allow_failures:
    - rvm: 1.9.2

script: "./bin/ci"

branches:
  only:
    - master
    - stable

